### ISSUE TITLE
Allow customization of the description prefix

### ISSUE THREAD

**Issue by djmitche** [taskcluster/tc-admin#15]
In https://github.com/taskcluster/tc-admin/blob/d35c775020e9a67086e58bd91203a7b611803187/tcadmin/resources/util.py#L16-L20 we add a prefix to every description that basically says "don't edit this".  We would like to allow users to customize this prefix in `tc-admin.py`, similar to how they can customize `check_path`: https://github.com/taskcluster/tc-admin/blob/d35c775020e9a67086e58bd91203a7b611803187/tcadmin/appconfig.py#L90

**Comment by zbeproud** [comment]
@djmitche As I said earlier I am a noob and wanted to start contributing. Could you please give me a few pointers on how I should begin?

**Comment by djmitche** [comment]
Sure!  A good place to start will be what Vikrant is doing in https://bugzilla.mozilla.org/show_bug.cgi?id=1467511 -- get a sample `tc-admin.py` set up and experiment with it.  Once that's working, you should see the "DO NOT EDIT' bit in the description of generated resources.

Then, have a look at how `check_path` is implemented and think about how you might implement something similar named, say, `description_prefix`.  The "magic" bit is how to get that value from the appconfig when you need it, without passing it from function to function to function to get it there. But even the magic isn't so hard -- here's how it's done for `check_path`:
https://github.com/taskcluster/tc-admin/blob/d92e66604fd7b6ce45fb2ff8854bfdf28161c772/tcadmin/check.py#L20

**Comment by djmitche** [comment]
@iamaadijo did you make any progress here?

**Comment by iamaadijo** [comment]
@djmitche Sorry, I have been tied up in exams. I will start with it next week. Is that ok?

**Comment by djmitche** [comment]
That's fine!

**Comment by kushthedude** [comment]
@djmitche Can I work on it?

**Comment by djmitche** [comment]
@iamaadijo will you be able to work on the issue this week?

**Comment by vishakhanihore** [comment]
@djmitche Can I try this one?

**Comment by djmitche** [comment]
No word from @iamaadijo.  @kushthedude if you would like to hack on this, please go ahead, otherwise sure @vishakhanihore!

**Comment by vishakhanihore** [comment]
@kushthedude Do you have any objection if I take over this ?

**Comment by akhil-code** [comment]
Hi, can I work on this ?

**Comment by kushthedude** [comment]
@vishakhanihore feel free to work on it.

**Comment by bhushan-borole** [comment]
Hello @djmitche 
I would like to work on this issue. Can you assign me this?

**Comment by djmitche** [comment]
Done!

**Comment by bhushan-borole** [comment]
> Done!

I will get the setup done and will get started with this.
Thank you!
