### ISSUE TITLE
Release with updated taskcluster dependency for Python 3.9

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/tc-admin#167]
tc-admin needs a release cut with taskcluster v39 to pick up https://github.com/taskcluster/taskcluster/pull/4109

A project specifying:

    taskcluster~=39.2.0
    tc-admin~=2.5.1

(which creates an impossible dependency on `taskcluster==39.*` and `taskcluster==30.*`) takes a **long** time to fail due to ongoing issues with the new pip dependency solver. I opened a pip issue for this at https://github.com/pypa/pip/issues/9346.

**Comment by djmitche** [comment]
https://pypi.org/project/tc-admin/2.6.0/
https://github.com/taskcluster/tc-admin/releases/tag/v2.6.0

Sorry for the delay!
