### ISSUE TITLE
Release with updated PyYAML dependency

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/tc-admin#174]
The current release (v2.6.0) requires `PyYAML ~= 5.3.1`, which means 5.4 is not accepted. Because PyYAML 5.4 is a security release, there should be a tc-admin update released to include it.

**Comment by djmitche** [comment]
2.6.1 is out :D

**Comment by jschwartzentruber** [comment]
Thanks! I accidentally merged a fix for a Github nag to update PyYAML and now I have broken dependencies.... which still hang pip....
