### ISSUE TITLE
Add utilities for writing checks

### ISSUE THREAD

**Issue by djmitche** [taskcluster/tc-admin#2]
[ci-admin defines](https://hg.mozilla.org/ci/ci-admin/file/tip/ciadmin/check/conftest.py) some pytest fixtures to get the current and generated resources.  Those will be universally necessary for writing checks, so let's include that functionality in tcadmin directly.

**Comment by kushthedude** [comment]
@djmitche Do we to include [ci-admin](https://hg.mozilla.org/ci/ci-admin/file/tip/ciadmin/check/conftest.py) in the `tc-admin` repo tests ?

**Comment by djmitche** [comment]
No, ci-admin is strictly a user of the `tc-admin` package.  Instead, let's copy those functions into tc-admin.

You can find an example of another use of tc-admin in https://github.com/mozilla/community-tc-config/.  It might be good to get that repo checked out and make sure you can run `tc-admin diff` correctly, and perhaps work on https://github.com/mozilla/community-tc-config/issues/5 so that there is a check in the repo.  In the process of getting that to work, you should see what code you need to copy from ci-admin.

**Comment by djmitche** [comment]
It turns out we really don't use checks in tc-admin, so I don't think there's useful work to do here.
