### ISSUE TITLE
Support callbacks on apply

### ISSUE THREAD

**Issue by La0** [taskcluster/tc-admin#67]
The [fuzzing-tc](https://github.com/MozillaSecurity/fuzzing-tc) project needs to run some actions before or after changes have been applied with tc-admin:

1. cancel running tasks in a worker pool if it will be modified
2. trigger hooks once they are created / modified
3. ... maybe more actions later ?

We could implement that around tc-admin, but i think it could also be done by adding some callbacks functionality in the `apply` workflow.

An external repository would add some declarations in its local `tc-admin.py` :

```python
appconfig.callbacks.before_apply.add(clear_tasks, actions=["update", "delete"], resources=[WorkerPool])
appconfig.callbacks.after_apply.add(trigger_hooks, actions=["update", "create"], resources=[Hook])
```

Each callback function would then receive a list of filtered resources if any matches the actions & resources type filter during the apply execution.

The `tcadmin/update.py` file seem like the obvious choice to trigger those callbacks.

@djmitche Would you be OK with a PR for this behaviour ?

**Comment by djmitche** [comment]
Yeah, that sounds pretty cool :)
